### ISSUE TITLE
The new embeddings

### ISSUE THREAD

**Issue by MehdiBehfar1** [zshicode/GNN-for-text-classification#1]
Hi,
as we know GNNs update the embeddings. How the new embeddings can be taken after training?

Thank you so much.

**Comment by zshicode** [comment]
As written in README.md, this repository is based on TextGCN. So you can refer to TextGCN paper for details.

**Comment by MehdiBehfar1** [comment]
Thank you for your time. I have read the paper. My question is about the impelementation. 
After training the model, the new embedding of each word how can be saved for future use?
