### ISSUE TITLE
AttributeError: module 'dgl.function' has no attribute 'src_mul_edge'

### ISSUE THREAD

**Issue by NitishOritro** [zshicode/GNN-for-text-classification#11]
![image](https://user-images.githubusercontent.com/18516222/226939790-323cf13f-b267-4a68-826d-81e860e15e26.png)

While training on google collab, I faced this problem. I have imported all the this that you provided in your repo. Please help me.

**Comment by zshicode** [comment]
Code in this repository is based on previous version of PyTorch and DGL. The code is run on PyTorch 1.3.1 with CUDA 10.1 and DGL 0.4.1. So if you use the latest version of PyTorch and DGL to run the code, some bugs may occur.

**Comment by NitishOritro** [comment]
I have solved it.  

def __init__(self,g,in_feats,out_feats,activation):
        g.update_all(fn.u_mul_e('h', 'w', 'm'), fn.sum(msg='m',out='h'))

def forward(self,feat):
        g.update_all(fn.copy_u('h', 'm'), fn.sum('m', 'neigh'))

Here My repo:
CUDA Version: 12.0  
dgl-1.0.1
