### ISSUE TITLE
使用GPU的问题，数据无法导入GPU

### ISSUE THREAD

**Issue by 2411900147W** [zshicode/GNN-for-text-classification#14]
使用GPU设备加速时
在logits = model(t_features)中，出现了Cannot assign node feature "h" on device cuda:0 to a graph on device cpu. Call DGLGraph.to() to copy the graph to the same device.使用CPU运行程序没有这个问题。请您指点，我无法找到并且修改数据导入的设备，谢谢！！  此外，由于版本问题，我使用的是cuda116，py10，所以可能会存在不兼容的问题

**Comment by zshicode** [comment]
这个repo的代码基于PyTorch和DGL的旧版本：PyTorch 1.3.1，CUDA 10.1和DGL 0.4.1。如果使用最新版本的PyTorch和DGL，可以参考PyTorch和DGL的官方文档来修改代码

**Comment by 2411900147W** [comment]
好的，谢谢您的指点，我会尝试DGL和PyTorch修改此代码。此外，程序在处理大规模的文本数据，比如说3w条以上本文数据时，由于没有batch_size的原因，会有内存不够的问题。
