### ISSUE TITLE
Running on Google Colab:dgl._ffi.base.DGLError: Cannot assign node feature "h" on device cuda:0 to a graph on device cpu. Call DGLGraph.to() to copy the graph to the same device.

### ISSUE THREAD

**Issue by richachoudhary** [zshicode/GNN-for-text-classification#5]
Running on Google Colab, the following issue occurs in main.py. Cuda is working fine in colab, but the way it is called on graphs might not be the correct way ?

DGL backend not selected or invalid.  Assuming PyTorch for now.
Setting the default backend to "pytorch". You can change it in the ~/.dgl/config.json file or export the DGLBACKEND environment variable.  Valid options are: pytorch, mxnet, tensorflow (all lowercase)
Using backend: pytorch
(181, 300) (181, 1) (99, 300) (99, 1) (2423, 300) (2423, 1)
2522
/usr/local/lib/python3.7/dist-packages/dgl/base.py:45: DGLWarning: Recommend creating graphs by `dgl.graph(data)` instead of `dgl.DGLGraph(data)`.
  return warnings.warn(message, category=category, stacklevel=1)
Classifer(
  (gcn1): SimpleConv()
  (gcn2): SimpleConv()
)
Traceback (most recent call last):
  File "main.py", line 305, in <module>
    logits = model(t_features)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "main.py", line 235, in forward
    x = self.gcn1(features)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "main.py", line 118, in forward
    g.ndata['h'] = feat.mm(getattr(self, 'W'))
  File "/usr/local/lib/python3.7/dist-packages/dgl/view.py", line 81, in __setitem__
    self._graph._set_n_repr(self._ntid, self._nodes, {key : val})
  File "/usr/local/lib/python3.7/dist-packages/dgl/heterograph.py", line 3811, in _set_n_repr
    ' same device.'.format(key, F.context(val), self.device))
dgl._ffi.base.DGLError: Cannot assign node feature "h" on device cuda:0 to a graph on device cpu. Call DGLGraph.to() to copy the graph to the same device.

**Comment by zshicode** [comment]
Code in this repository is based on previous version of PyTorch and DGL. The code is run on PyTorch 1.3.1 with CUDA 10.1 and DGL 0.4.1. So if you use the latest version of PyTorch and DGL to run the code, some bugs may occur.
