### ISSUE TITLE
tcmalloc: large alloc x bytes == y bytes

### ISSUE THREAD

**Issue by ghost** [zshicode/GNN-for-text-classification#8]
this error keeps on showing, I'm running it on Google Colab (GPU) this allocation error keeps showing even If I set the embedding dimentions to 5 for example, I've tried it on my pc and the same error 

tcmalloc: large alloc 6927122432 bytes == 0xb3e8000 @  0x7f3ed2b9d001 0x7f3ecf8ed1af 0x7f3ecf943c23 0x7f3ecf944a87 0x7f3ecf9e6823 0x5936cc 0x548c51 0x5127f1 0x593dd7 0x548ae9 0x51566f 0x549576 0x593fce 0x548ae9 0x51566f 0x4bc98a 0x59c019 0x59588e 0x595b69 0x531d8c 0x511ee1 0x593dd7 0x5118f8 0x549576 0x604173 0x5f5506 0x5f8c6c 0x5f9206 0x64faf2 0x64fc4e 0x7f3ed2798c87
tcmalloc: large alloc 6927122432 bytes == 0x7f3c931c8000 @  0x7f3ed2b9d001 0x7f3ecf8ed1af 0x7f3ecf943c23 0x7f3ecf944a87 0x7f3ecf9e6823 0x5936cc 0x548c51 0x5127f1 0x593dd7 0x548ae9 0x51566f 0x549576 0x593fce 0x548ae9 0x51566f 0x4bc98a 0x59c019 0x59588e 0x595b69 0x531d8c 0x511ee1 0x549576 0x604173 0x5f5506 0x5f8c6c 0x5f9206 0x64faf2 0x64fc4e 0x7f3ed2798c87 0x5b621a
^C

**Comment by zshicode** [comment]
This may occur if there is a great deal of memory in the server, and it may be necessary to apply some tricks for saving the memory.

**Comment by ghost** [comment]
I did not change anything in your code, I use it as it is. 
I am running it on Goolge Colab in GPU mode and I have installed the old pytorch and dgl versions you used
I applied it on "mr" dataset that you provided.
The program didn't even start and showed "tcmalloc" memory error
What kind of tricks to add to save the memory ?
