### ISSUE TITLE
Result

### ISSUE THREAD

**Issue by Sreelakshmi-k** [zshicode/GNN-for-text-classification#9]
I am able to run your code, but where can i find the results. 
The results folder is empty after running the code. The accuracy doesn't get printed.

After running the code i get the below 2 lines.

tcmalloc: large alloc 6927122432 bytes == 0x20158000 @  0x7f46e6edf001 0x7f46e433a22f 0x7f46e439268b 0x7f46e43934f7 0x7f46e4435913 0x5aae14 0x49abe4 0x4fd2db 0x4997c7 0x4fd8b5 0x4997c7 0x5d8868 0x4fe318 0x4eafcf 0x5d935e 0x5872ea 0x55e029 0x5d8868 0x4990ca 0x55cd91 0x55d743 0x642630 0x6426ae 0x644b78 0x64511c 0x677e5e 0x678029 0x7f46e6adac87 0x5e1baa
tcmalloc: large alloc 6927122432 bytes == 0x1bd812000 @  0x7f46e6edf001 0x7f46e433a22f 0x7f46e439268b 0x7f46e43934f7 0x7f46e4435913 0x5aae14 0x49abe4 0x4fd2db 0x4997c7 0x4fd8b5 0x4997c7 0x5d8868 0x4fe318 0x4eafcf 0x5d935e 0x5872ea 0x55e029 0x55cd91 0x55d743 0x642630 0x6426ae 0x644b78 0x64511c 0x677e5e 0x678029 0x7f46e6adac87 0x5e1baa
^C

Could you please help me with this.

**Comment by zshicode** [comment]
This may be because the versions of dependency libraries (e.g. PyTorch or DGL) on your computer is not consistent to this repository (see README.md for the detail of dependency libraries), or because the GPU memory of your computer is not enough to run the bigger dataset.
